### PR TITLE
Adding MultiCounter: A Counter with colourful sub-counters

### PR DESCRIPTION
**Pull request by djoffe**
MultiCounter allows to have a single counter that displays more info by introducing colour. Something like this:
image

I added an example, but no tests or documentation yet.
Code reviews more than welcome!

### CODE REVIEW

**Comment by avylove** [comment]
Thanks for the pull request! Great idea! I'm traveling now so it might take me a little while to be able to do a proper review, but I'll take a deeper look as soon as I get a chance.

**Comment by avylove** [comment]
I think the idea is great, but I'm not sure about the approach. Mainly I wasn't sure this needed to be a subclass of Counter. Instead I thought it would be better just to add the functionality to the Counter class. I also wasn't sure about the mechanics of use. Please take a look at the [multicolor branch](https://github.com/Rockhopper-Technologies/enlighten/tree/multicolor), specifically the [multicolored.py](https://github.com/Rockhopper-Technologies/enlighten/blob/multicolor/examples/multicolored.py) example. Let me know if this will fit your needs and if you have any ideas for improvement.
I still need to add test code and I should add an example in the main docs (API docs have been updated). Hopefully I'll get a chance to do that soon, but I'm still travelling, so coding time is inconsistent.

**Comment by avylove** [comment]
Added tests to the [multicolor branch](https://github.com/Rockhopper-Technologies/enlighten/tree/multicolor). Just need to add some documentation. @djoffe, let me know if there is any functionality missing and I can try to fit it in. Otherwise, I'm hoping to get this in a new release with a couple other things by the end of March. Really just depends how much time I get to work on it.

I forgot to point out the branch version also allows coloring the bar when subcounters are not used and adds additional format fields: Percentage and count for each subcounter as well as the remainder of each in the parent counter. Optionally, rate of each sub bar and eta (assuming the subcounter count will eventually equal the total for the parent)

**Comment by avylove** [comment]
[Version 1.2.0](https://github.com/Rockhopper-Technologies/enlighten/releases/tag/1.2.0) is out. It has the multicolored counter support. Thanks for the idea. I hope it's useful for you. Let me know if any issues come up.

**Comment by djoffe** [comment]
I am so sorry for the very long delay, I haven't had time to look at it until quickly this week!
I just gave 1.3.0 a try and it is great :)

Thanks!

**Comment by avylove** [comment]
No worries! Thanks for the suggestion!

**Pull request closed without merging**
