### PR TITLE
add appveyor CI config

### PR DESCRIPTION
**Pull request by Borda**
later also add the badge (using mine just for this branch [Build status](https://ci.appveyor.com/project/Borda/enlighten/branch/CI-appveyor) )
see sample https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

### CODE REVIEW

**Comment by Borda** [comment]
https://help.appveyor.com/discussions/problems/24208-unable-to-use-the-latest-version-of-pip-for-my-tox-builds

**Comment by avylove** [comment]
I'm glad you got your build working. And I do think Enlighten needs some testing on Windows, but I think you're missing the goal here. Adding an Appveyor config is pretty easy, the hard part is coming up with relevant tests to run on Windows. Most of the testing involves creating PTYs which is easy on Linux, but the capability was just added to Windows 10 a year ago (It's also in Server 2019). So the options are to make the current tests work by figuring out how to use a similar capability and run the tests on Server 2019 or create a general use test essentially to make sure nothing breaks. Probably both would be good to have in the longer term, though a general use test would be easier to implement in the short term. Perhaps running one of the example scripts would be sufficient.

If you're going to work on this, that would be awesome, otherwise I'll add it to my todo list and close this PR.

**Comment by Borda** [comment]
Well I have started with adding working config and it seems that the tests are not passing so I was wondering if you are going to fix them before we would add another test...

**Comment by avylove** [comment]
As explained before, the tests aren't broken, they use lower level Linux calls to create a pseudo terminal. They weren't designed to run on Windows and making them run on Windows is not a minor effort. A basic functionality test would be the place to start rather than trying to run the whole test suite. So if you'd like to tackle that, it would be appreciated, but otherwise I think this request is putting the cart before the horse.

**Pull request closed without merging**
